### PR TITLE
Add support for shaarli2mastodon

### PR DESCRIPTION
**Pull request by angristan**
I opened #34 a year ago and I still use Shaarli and Mastodon every day.

I recently started learning Java at school as well as a little bit of Android development.

Since I am a bit more comfortable with the language and the structure of Android apps, I tried to fix this issue myself!

Overall it's a copy/paste of the `shaarli2twitter` feature. I was able to test it on my phone on Pie and can confirm it's perfectly working! 🎉 

I hope I did not make hideous stuff and that you will accept my PR 😄

### CODE REVIEW

**Comment by angristan** [comment]
PS: Android Studio made all these changes to `app/app.iml` when bulding the app. I don't know if I should have committed them or not.

**Comment by angristan** [comment]
This is how it looks:

Screenshot_20190413-003935_30
Screenshot_20190413-003945_2_30

**Comment by dimtion** [comment]
First of all, I would like to give you a big shout-out for this pull request. Since I don't have a Mastodon account, I did not take the time to fix this issue that is awaited by a lot of people.

I have read the PR, it looks good to me, I'll try to test and merge it if I have more time tomorrow.

Thanks again!

**Comment by dimtion** [comment]
Oh, yeah I have one question: is "toot" the equivalent to "tweet" in Mastodon vocab?

**Comment by angristan** [comment]
Awesome! Yes, a toot is the equivalent of a tweet.

Screenshot 2019-04-13 at 14 44 42

**Review by dimtion — APPROVED** [review]

**Pull request merged**
