### PR TITLE
Add Basic Auth support for Shaarli servers

### PR DESCRIPTION
**Pull request by sbarakat**
Thank you for creating such a simple to use app!

I have recently been playing around with a Shaarli server and have it setup behind HTTP Basic Auth. When I tried out the Shaarlier app I noticed Basic Auth wasn't supported, so I've gone ahead and added it.

I've done some light testing so far and it seems to work well. I still need to handle database upgrades correctly, so I'm hoping to finish it off soon. I thought I'd create this pull request now to give you a heads up and for you to let me know if you would like anything changed. If you'd like this on a different branch let me know and I'll try to move it.

Cheers!

### CODE REVIEW

**Comment by mro** [comment]
@sbarakat just curious (I'm the author of a similar thing for iOS - https://github.com/mro/ShaarliOS) - what's the benefit of HTTP Basic compared to the proprietary shaarli auth?

Digest or CRAM-SHA would IMO be interesting, however.

**Comment by sbarakat** [comment]
@mro thanks for the question. I run various web apps within directories on a single domain and have everything behind HTTP Basic over SSL. This has the advantage of only needing to purchase a single SSL certificate and adds an extra layer of protection in case a vulnerability is found in any of the apps.

Plus I've found it's a really good way to avert bots indexing anything that may have been accidentally made "public". It's trivially easy finding shaarli installations, this is no fault of shaarli, just search engines doing their thing. HTTP Basic allows it to be a little more hidden and shaarli auth doesn't help here, however robots.txt or noindex headers could work if all bots respected that.

Adding Digest or CRAM-SHA may be a possibility, the Shaarlier app could detect which type to use then send the credentials in that format. This could be implemented if needed, however Basic is pretty much the simplest and well supported setup on webservers, so is a good start. (the tt-rss app for android for example, [only supports Basic](https://tt-rss.org/gitlab/fox/tt-rss-android/blob/master/org.fox.ttrss/src/main/java/org/fox/ttrss/ApiRequest.java#L169))

**Comment by dimtion** [comment]
Thanks for the pull request,  

So I've started reviewing your code and I have some remarks to say.  
Firstly, it is purely cosmetic but wouldn't it be better if the "basic authentication" fields were in an advanced hidden category ? In tiny bug I've found : create a new account without HTTP basic Auth, save it then edit back this account, the HTTP basic Auth switch will be activated.

Other than that, I'm just afraid that you opened my eyes on a problem with my network classes : they are not very factored, reading your code I was thinking that there are a lot of duplicated code. Also, the fact that you had to edit most of the HMI classes made me realize that the network interface is not optimal. Maybe in the future it could be better just to pass a `ShaarliAccount` parameter than a bunch of strings.  

For the next release I will leave it like that, but I'm working right now on this problem in the NetworkService branch.  
About Digest or CRAM-SHA, what are the advantages of those over basic auth with HTTPS ? Isn't HTTPS enough to secure the connection ? For the moment I have not received any request for adding them, so I don't think it is worth spending time on them right now.

Thanks again for the the pull request !

**Comment by mro** [comment]
@dimtion HTTPS definitively is superior, but there are hosting situations where it comes at quite some financial and organizational cost for each server. Installing in a subdir mitigates this a bit. But if only the password needs protection (imagine posting links on a publi shaarli) CRAM would IMO be an interesting option.

So the advantages of CRAM are:
- CRAM keeps password safe on the wire without no external requirements.

**Comment by sbarakat** [comment]
@dimtion it was initially my thought to have the toggle switch collapse/expand the basic auth username and password fields, however when I got the fields on the screen I didn't think it looked too bad. Also the "Manage Accounts" area is so infrequently visited that I didn't want to over think it. Could you describe how an advanced category would work? I'm happy for the basic auth settings to live anywhere really, so long as the ui is simple. Plus thanks for pointing out the bug! I'll get a fix in.

I strongly agree that passing around a `ShaarliAccount` would be better practice to allow it to be extended in such a way. When I worked on this I followed the current coding style in the hope of the pull request being accepted. There are a some areas that could do with refactoring, however I don't know the code well enough to make big alterations like that. The NetworkService branch looks good! Given more time I'd be happy to push other pull requests as I see areas that can be refactored or adding new features.

Perhaps instead of cluttering the "Manage Accounts" interface with options for Basic, Digest and anything else that may come down the line (like self signed certs), it could instead simply ask for a url to a Shaarli installation and detect which types of authentication is being used then present those fields/options for the user to fill out. This is perhaps a lot of re-work, so I'm not suggesting to do it now, however it would be interesting to explore from a ui point of view.

@mro I think there's been some confusion along the way. If we are talking about CRAM authentication, it is mostly used in email servers to authenticate over POP or IMAP. For HTTP authentication there is really only the options of Basic or Digest. [Apache supports both](http://httpd.apache.org/docs/2.4/howto/auth.html), while [nginx support Basic](http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html) out of the box and [Digest using a third party module](https://www.nginx.com/resources/wiki/modules/auth_digest/).
In my opinion if people were going the route of securing their install for minimal costs they would opt for a self signed cert with HTTP authentication. Either Basic or Digest isn't going to make much difference here as the trust is with the server and the password isn't going over the wire in plain text, however this is still open to MITMA.

**Comment by mro** [comment]
@sbarakat sorry for the confusion, I'm talking about CRAM-like auth as a replacement for the shaarli-build-in custom auth mechanism. Not related to webserver auth. (I find it appealing but maybe not worth while the necessary work once @letsencrypt arrives)

**Comment by dimtion** [comment]
@sbarakat I have merged the pull request into NetworkService. I don't close this pull request in case you have any remarks.

If you want to edit the pull request you should probably rebase your fork, I have made many changes in the meantime and merging them is quite painful.

Thanks again for the contribution !

**Comment by sbarakat** [comment]
Thank you very much for putting this in! I'm on 1.3.0 and it works great!

**Pull request merged**
